<?
$aMenuLinks = Array(
	Array(
		"LCD/DLP", 
		"/products/materialy/filter/section-is-lcd_dlp/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"SLA", 
		"/products/materialy/filter/section-is-sla/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Cast", 
		"/products/materialy/filter/areas_use-is-burned-out/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Dental", 
		"/products/materialy/filter/areas_use-is-stomatologiya/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Model", 
		"/products/materialy/filter/areas_use-is-modelirovanie/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Jewelry", 
		"/products/materialy/filter/areas_use-is-yuvelirnoe-delo/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Industrial", 
		"/products/materialy/filter/areas_use-is-promyshlennost/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Merch", 
		"/products/merch/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Test materials", 
		"/products/test-materials/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Pre-order", 
		"/products/preorder/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"New", 
		"/products/new/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>